version: "3"

services:
  main:
    container_name: mainApp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis
      - PORT=4002
      - JWT_ACCESS_SECRET="123"
      - JWT_REFRESH_SECRET="321"
      - ACCESS_TOKEN_LIFE=30m
      - REFRESH_TOKEN_LIFE=60m
      - SALT=2
    ports:
      - 8080:4002
    command: ["node", "src/index.js"]

    depends_on:
      - redis
    
    restart: always

  redis:
    image: redis/redis-stack:latest
    restart: always




